Contacts.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Contacts.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Contacts.Web/Pages/Index.cshtml.cs
using Contacts.Shared.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Tarim11.WEB.Extensions;

namespace Contacts.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IRequestAPI requestAPI;

        public List<Person> persons { get; set; }

        public IndexModel(IRequestAPI requestAPI, ILogger<IndexModel> logger)
        {
            _logger = logger;
            this.requestAPI = requestAPI;
        }

        public async Task OnGetAsync()
        {
            persons=await requestAPI.getListAsync<Person>("GetAllPersons?page=0&size=0");
        }

        public async Task<IActionResult> OnGetRemovePersonAsync(Guid guid) {
            var result = await requestAPI.DeleteItemAsync($"DeletePerson?id={guid}");

            return result;
        }
    }
}

Contacts.Web/Pages/person.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Contacts.Web.Pages
{
    public class personModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Contacts.Web/Pages/Index.cshtml
@page
@using Contacts.Shared.Entities
@model IndexModel
@{
    ViewData["Title"] = "Persons List";
}

<div class="text-center">
    <h1 class="display-4">Persons List</h1>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>SurName</th>
                <th>Company</th>
                <th>Edit</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Person person in Model.persons)
            {
                <tr>
                    <td>@person.Name</td>
                    <td>@person.Surname</td>
                    <td>@person.Company</td>
                    <td><a class="btn btn-primary" asp-page="person" asp-route-ID="@person.UUID" >Edit</a> </td>
                    <td><a class="btn btn-danger" asp-page="index" asp-route-ID="@person.UUID" asp-page-handler="removePerson">Remove</a> </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Contacts.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contacts.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Contacts.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Contacts List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Contacts.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Contacts.Web/Pages/person.cshtml
@page
@model Contacts.Web.Pages.personModel
@{
    ViewData["Title"] = "Add Or Delete Person";
}